import Head from "next/head";
import Header from "@/components/Header";
import Row from "@/components/Row";
import TopicsRow from "@/components/TopicsRow";
import usePreferredTopics from "@/hooks/usePreferredTopics";
import BookmarksRow from "@/components/BookmarksRow";

const Discovery = () => {
  const { preferredTopics } = usePreferredTopics();
  const topics = ["Vue", "TypeScript", "JavaScript", "Go", "CSS", "Node"];

  return (
    <div className="relative h-screen">
      <Head>
        <title>Sword Health Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="py-32 space-y-12">
        <BookmarksRow />
        <section>
          <TopicsRow topics={topics} />
        </section>
        <section className="flex flex-col gap-4">
          {preferredTopics &&
            preferredTopics.map((topic, index) => (
              <Row key={index} topicName={topic.id} sortedBy={topic.sortBy} />
            ))}
        </section>
      </main>
    </div>
  );
};

export default Discovery;
